### ISSUE TITLE
Request: 📄 More details in test results (e.g., description, tag, and annotation)

### ISSUE THREAD

**Issue by rdhar** [estruyf/playwright-github-actions-reporter#10]
Hi @estruyf, big fan of your project and surprised it isn't adopted as the "official" `github` reporter! It's the go-to for optimising the output of running Playwright tests in GH Action workflow.

### Summary

One area I'm especially keen on is adding some more detailed description around the test results. For example, here's an example test script using `test.describe`, `tag`(s), and `annotation`(s).

### Steps to replicate

```ts
// example.spec.ts
import { test, expect } from "@playwright/test";

test.describe("navigation", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("https://playwright.dev/");
  });

  test("has url", { tag: ["@example", "@smoke"] },
    async ({ page }) => {
      await expect(page).toHaveURL("https://playwright.dev/");
    }
  );

  test("get started link", {
    tag: "@example",
    annotation: {
      type: "docs",
      description: "https://playwright.dev/docs/writing-tests",
    },
  },
    async ({ page }) => {
      await page.getByRole("link", { name: "Get started" }).click();
      await expect(
        page.getByRole("heading", { name: "Installation" })
      ).toBeVisible();
    }
  );
});
```

### Current behaviour

And here's the associated output from this project's custom reporter for this test.

<table><tr><th>Test</th><th>Status</th><th>Duration</th><th>Retries</th></tr><tr><td>has url</td><td>✅ Pass</td><td>0.850s</td><td></tr><tr><td>get started link</td><td>✅ Pass</td><td>1.318s</td><td></tr></table>

### Proposed behaviour

Compared to the `list` built-in reporter output for this test.

```sh
  ✓  1 [chromium] › example.spec.ts:10:7 › navigation › has url (850ms)
  ✓  2 [chromium] › example.spec.ts:17:7 › navigation › get started link (1.3s)

  2 passed (2.0s)
```

It'd be swell if the test results table could include some of these extra details, perhaps in this layout?

| Test                          | Status | Duration | Retries | Tag             |
| ----------------------------- | ------ | -------- | ------- | --------------- |
| navigation > has url          | ✅ Pass | 0.850s   | 0       | example smoke |
| navigation > get started link | ✅ Pass | 1.318s   | 0       | example smoke |

### Attachments

For reference, here's the `html` built-in reporter output screenshot for the second test with `tag` and `annotation`.

![image](https://github.com/estruyf/playwright-github-actions-reporter/assets/19497993/1569e742-eefa-4ce0-8db2-53fcb6554e6e)

Many thanks for your time and consideration for continuously improving this project!

**Comment by rdhar** [comment]
### Context

For some added background, this is especially useful when iterating through tests in a `for` loop to validate multiple environments simultaneously, for example.

```ts
// example.spec.ts
import { test, expect } from "@playwright/test";

const envs = ['dev', 'stg', 'prd'];
for (const env of envs) {
  test.describe(`${env}: navigation`, () => {
    test.beforeEach(async ({ page }) => {
      await page.goto("https://playwright.dev/");
    });
  
    test("has url", { tag: ["@example", "@smoke"] },
      async ({ page }) => {
        await expect(page).toHaveURL("https://playwright.dev/");
      }
    );
  });
};
```

### Expected behaviour

Which returns the following `list` reporter output.

```sh
✓  1 [chromium] › example.spec.ts:12:9 › dev: navigation › has url (850ms)
✓  2 [chromium] › example.spec.ts:12:9 › stg: navigation › has url (850ms)
✓  2 [chromium] › example.spec.ts:12:9 › prd: navigation › has url (850ms)
```

### Current behaviour

Whereas, this project's custom reporter is ambiguous, at best.

<table><tr><th>Test</th><th>Status</th><th>Duration</th><th>Retries</th></tr><tr><td>has url</td><td>✅ Pass</td><td>0.850s</td><td></tr><tr><td>has url</td><td>✅ Pass</td><td>0.850s</td><td></tr><tr><td>has url</td><td>✅ Pass</td><td>0.850s</td><td></tr></table>

**Comment by estruyf** [comment]
I wasn't aware of the annotation and tagging functionality, but I noticed it has recently been released. I will integrate support into the reporter. Thanks for the suggestion.

**Comment by rdhar** [comment]
Thanks for responding so quickly, @estruyf, that's great to hear! 

Although, I understand that integrating both `tag` and `annotation` can get a bit messy in the test results table, so might take some thinking through.

Even the inclusion of the long-standing `test.describe` [parameter](https://playwright.dev/docs/api/class-test#test-describe) as a prefix to the test names would be ideal to bring feature parity up with the built-in `list` reporter.

**Comment by estruyf** [comment]
For the table, I have an idea for it. 

| Test | Status | Duration | Retries | 
| --- | --- | --- | --- |
| The annotation (full colspan) |||
| Title |  ✅ Pass | 0.850s | |

**Comment by estruyf** [comment]
Looks as follows:

<img width="692" alt="image" src="https://github.com/estruyf/playwright-github-actions-reporter/assets/2900833/f63a4b16-c789-4c80-a4e9-41e2b9e26bb7">

**Comment by rdhar** [comment]
Oh, nice! I was considering an unordered list for the annotations, but I think yours might look better actually.

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>Status</th>
      <th>Duration</th>
      <th>Retries</th>
      <th>Tag</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      
      <td colspan="5">
        <ul>
          <li>docs: https://playwright.dev/docs/writing-tests</li>
          <li>issue: https://github.com/estruyf/playwright-github-actions-reporter/issues</li>
        </ul>
      </td>
    </tr>
    <tr>
      <td>(dev) navigation > has url</td>
      <td>✅ Pass</td>
      <td>0.850s</td>
      <td>0</td>
      <td>example, smoke</td>
    </tr>
    <tr>
      <td>(stg) navigation > has url</td>
      <td>✅ Pass</td>
      <td>0.850s</td>
      <td>0</td>
      <td>example, smoke</td>
    </tr>
    <tr>
      <td>(prd) navigation > has url</td>
      <td>✅ Pass</td>
      <td>0.850s</td>
      <td>0</td>
      <td>example, smoke</td>
    </tr>
  </tbody>
</table>

**Comment by estruyf** [comment]
I released a beta version with support for annotations and tags. Feel free to give it a try by installing: `@estruyf/github-actions-reporter@1.5.1-beta.8205947`.

Nothing on your end has to be changed in the configuration, but I have added the following options to disable it:

```ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: [
    ['@estruyf/github-actions-reporter', {
      showAnnotations: false,
      showTags: false
    }]
  ],
});
```

**Comment by rdhar** [comment]
Unbelievably quick turnaround: that totally worked! 🚀 
Here's the beta reporter's output using my tweaked example.spec.ts.

<table role="table">
<thead>
<tr>
<th>Test</th>
<th>Status</th>
<th>Duration</th>
<th>Retries</th>
<th>Tags</th>
</tr>
</thead>
<tbody>
<tr>
<td>(dev) navigation > has url</td>
<td>✅ Pass</td>
<td>10.398s</td>
<td></td>
<td>example</td>
</tr>
<tr>
<td colspan="5"><strong>docs</strong>: https://playwright.dev/docs/writing-tests</td>
</tr>
<tr>
<td>(dev) navigation > get started link</td>
<td>✅ Pass</td>
<td>17.443s</td>
<td></td>
<td>dev, example, smoke</td>
</tr>
<tr>
<td>(stg) navigation > has url</td>
<td>✅ Pass</td>
<td>10.483s</td>
<td></td>
<td>example</td>
</tr>
<tr>
<td colspan="5"><strong>docs</strong>: https://playwright.dev/docs/writing-tests</td>
</tr>
<tr>
<td>(stg) navigation > get started link</td>
<td>✅ Pass</td>
<td>19.367s</td>
<td></td>
<td>stg, example, smoke</td>
</tr>
<tr>
<td>(prd) navigation > has url</td>
<td>✅ Pass</td>
<td>10.604s</td>
<td></td>
<td>example</td>
</tr>
<tr>
<td colspan="5"><strong>docs</strong>: https://playwright.dev/docs/writing-tests</td>
</tr>
<tr>
<td>(prd) navigation > get started link</td>
<td>✅ Pass</td>
<td>18.418s</td>
<td></td>
<td>prd, example, smoke</td>
</tr>
</tbody>
</table>

The bold on the annotation key is especially neat for ease of visual separation.
Massive thank you once again for looking into this in the first place!

**Comment by estruyf** [comment]
> The bold on the annotation key is especially neat for ease of visual separation.

I know and this is how I created it, but when having one annotation, GitHub is not picking it up for some reason and just shows: `**docs**`.

When having two annotations on the same line, it works. Have been trying to trick it, but wasn't successful. That is why I reverted it back to just the `type: description`.

![image](https://github.com/estruyf/playwright-github-actions-reporter/assets/2900833/5eef4bf0-6da3-49c5-a092-6d4b714ad66b)

**Comment by rdhar** [comment]
Oh that's interesting, and you gave unordered lists a go as well? 

Does it make any difference between using `<strong></strong>` compared to `<b></b>`, if that's even possible?

**Comment by estruyf** [comment]
That seems to work, I'm releasing a new beta

**Comment by estruyf** [comment]
This `@estruyf/github-actions-reporter@1.5.1-beta.8206408` release should include it.

**Comment by rdhar** [comment]
Markdown/HTML interpolation is a riddle, wrapped in a mystery, inside an enigma...

**Comment by rdhar** [comment]
With `1.5.1-beta.8206408`, the output looks golden as before, only using `<b>` instead of `<strong>`.
It'd be neat to have the links be clickable like `<a href...`, but I suspect that's a GH Action summary limitation.

<table role="table">
  <thead>
    <tr>
      <th>Test</th>
      <th>Status</th>
      <th>Duration</th>
      <th>Retries</th>
      <th>Tags</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>(dev) navigation > has url</td>
      <td>✅ Pass</td>
      <td>6.201s</td>
      <td></td>
      <td>example</td>
    </tr>
    <tr>
      <td colspan="5"><b>docs</b>: https://playwright.dev/docs/writing-tests</td>
    </tr>
    <tr>
      <td>(dev) navigation > get started link</td>
      <td>✅ Pass</td>
      <td>11.548s</td>
      <td></td>
      <td>dev, example, smoke</td>
    </tr>
    <tr>
      <td colspan="5"><b>docs</b>: https://playwright.dev/docs/writing-tests</td>
    </tr>
    <tr>
      <td>(stg) navigation > get started link</td>
      <td>✅ Pass</td>
      <td>11.399s</td>
      <td></td>
      <td>stg, example, smoke</td>
    </tr>
    <tr>
      <td>(prd) navigation > has url</td>
      <td>✅ Pass</td>
      <td>6.426s</td>
      <td></td>
      <td>example</td>
    </tr>
    <tr>
      <td colspan="5"><b>docs</b>: https://playwright.dev/docs/writing-tests</td>
    </tr>
    <tr>
      <td>(prd) navigation > get started link</td>
      <td>✅ Pass</td>
      <td>12.262s</td>
      <td></td>
      <td>prd, example, smoke</td>
    </tr>
  </tbody>
</table>

Looking solid to me! 🚀

**Comment by estruyf** [comment]
It is using `<b>`.

For the links, are you using the details option or not? When you don't use it, GH will show links. For the details option I need to write more logic to support is.

**Comment by rdhar** [comment]
Ah, you're correct: I _am_ using `useDetails: true`.

But that's minor nice-to-have, that's not even in scope of this request. I didn't even think'd it be possible to bring tags, annotations _and_ descriptions into the test results output so quickly! 

While on that topic, I did have one question/request about the summary presentation.
![image](https://github.com/estruyf/playwright-github-actions-reporter/assets/19497993/19d23c9e-d4ad-4a54-9b14-97461984bf4d)

I prefer it be fairly minimal and focused on the test results themselves, As a result, I pass `title: " "` to get rid of the distracting title heading. However:

1. Since the `<h1> </h1` tags remain, so does its underline (as shown in the screenshot above). Would it be possible to opt for removing the title heading altogether? 
2. Speaking of heading, the lowercase "test summary" doesn't fit well with the rest of your polished output. Consider title case for "Test Summary"? Or perhaps even, `title` controls the naming of this summary title, rather than having another heading inside?

Again, these are out-of-scope suggestions, and I'd be more than happy to raise as a separate request to avoid "feature creep." Really grateful to have any of your effort on accepting this request at all! 

EDIT: Used my better judgement and raised #11 instead of shifting the goalposts on this successfully fulfilled request!

**Comment by estruyf** [comment]
Implemented markdown parsing for the details view. That way, the links will render and can be clicked:

![image](https://github.com/estruyf/playwright-github-actions-reporter/assets/2900833/4d1ae2a3-6915-4293-989e-fdb16ee539e3)

**Comment by estruyf** [comment]
Available in the latest beta.

**Comment by rdhar** [comment]
Using the latest [v1.5.1-beta.8209184](https://www.npmjs.com/package/@estruyf/github-actions-reporter?activeTab=versions), link parsing of within Markdown annotations totally works, even with `useDetails: true`, as shown below:

<details>
  <summary>✅ example.spec.ts (linux / chromium)</summary><br>
  <table role="table">
    <thead>
      <tr>
        <th>Test</th>
        <th>Status</th>
        <th>Duration</th>
        <th>Retries</th>
        <th>Tags</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>(dev) navigation > has url</td>
        <td>✅ Pass</td>
        <td>3.064s</td>
        <td></td>
        <td>example</td>
      </tr>
      <tr>
        <td>(dev) navigation > has title</td>
        <td>✅ Pass</td>
        <td>2.869s</td>
        <td></td>
        <td>dev, example</td>
      </tr>
      <tr>
        <td colspan="5">
          <p><strong>docs</strong>: <a
              href="https://playwright.dev/docs/writing-tests">https://playwright.dev/docs/writing-tests</a></p>
        </td>
      </tr>
      <tr>
        <td>(dev) navigation > get started link</td>
        <td>✅ Pass</td>
        <td>6.029s</td>
        <td></td>
        <td>dev, example, smoke</td>
      </tr>
    </tbody>
  </table>
</details>

Just looking forward to the official release now! 🚀 
And massive thanks once again for taking onboard all these requests/suggestions in the first place; genuinely appreciate it.

**Comment by estruyf** [comment]
@RDhar version 1.6.0 has been released! Thanks for the suggestion and testing! 🙏
