### ISSUE TITLE
Request: 🎨 Summary section presentation configuration

### ISSUE THREAD

**Issue by rdhar** [estruyf/playwright-github-actions-reporter#11]
Hi @estruyf, following on from #10, thought best to raise a dedicated request/suggestion instead of tacking on to the existing thread and "moving the goalposts."

### Current behaviour
![image](https://github.com/estruyf/playwright-github-actions-reporter/assets/19497993/7fc024cc-985a-4421-a2a4-618fe5e6d9c8)
_Screenshot of test summary section._

### Proposed behaviour 

I prefer it be fairly minimal and focused on the test results themselves, As a result, I pass `title: " "` to get rid of the distracting title heading. However:

1. Since the `<h1> </h1` tags remain, so does its underline (as shown in the screenshot above). Would it be possible to opt for removing the title heading altogether? 
2. Speaking of heading, the lowercase "test summary" doesn't fit well with the rest of your polished output. Consider title case for "Test Summary"? Or perhaps even, `title` controls the naming of this summary title, rather than having another heading inside?

Thanks once again for your time and actively supporting this project!

**Comment by estruyf** [comment]
@RDhar, thanks for the suggestions.

1. This is definitely something which can be accomplished.
2. This is something you control. The `test summary` comes from your GH Action job name + summary. So in your case, your GH Action probably has the name set to `test`.

**Comment by rdhar** [comment]
You make it look too easy! Using the:
- Latest [v1.5.1-beta.8209184](https://www.npmjs.com/package/@estruyf/github-actions-reporter?activeTab=versions)
- Input `title: ""`
- Set `Test` for the job name.

![image](https://github.com/estruyf/playwright-github-actions-reporter/assets/19497993/fd849ae9-c510-416c-96df-4e1eb8309c4d)

Which is just perfect, thank you!
