### ISSUE TITLE
Unable to run the item within a docker container

### ISSUE THREAD

**Issue by manishmitra13** [estruyf/playwright-github-actions-reporter#13]
@estruyf 

Thanks for coming back ,

Well , I do the same what is mentioned here : Do you run it like the following example: https://playwright.dev/python/docs/ci-intro#via-containers

Do I export the test report outside the containers and then you point the report to it? , I think that will be a feasible solution

**Comment by estruyf** [comment]
Hi @manishmitra13, the Python version does not seem to support the same reporters as the default Playwright version. I'm afraid it is not possible yet, or a new version of this reporter needs to be created in Python.

**Comment by estruyf** [comment]
Closing the issue as it is currently not possible to use it with Python.
