### ISSUE TITLE
Hide passing tests from the reporter

### ISSUE THREAD

**Issue by fspinillo** [estruyf/playwright-github-actions-reporter#17]
Is there anyway to hide passing tests? Can't see anything in the docs, but wanted to ask.

**Comment by estruyf** [comment]
@fspinillo No, there is no option for it, but it can always be added as an enhancement for the reporter.

**Comment by fspinillo** [comment]
That would be awesome if possible. I can also try to take a closer look over the reporter and see if I can add it in myself.

**Comment by estruyf** [comment]
@fspinillo project is open for contributions. If you have the time, feel free to take a look at it and I'll be more than happy to review it.

**Comment by estruyf** [comment]
@fspinillo I have included some changes to support your request. With the new `report` property on the reporter, you can define the test statuses you want to include in your summary.

By default, it will show `pass`, `fail`, `flaky`, and `skipped`.

```ts
import { defineConfig } from '@playwright/test';
import type { GitHubActionOptions } from '@estruyf/github-actions-reporter';

export default defineConfig({
  reporter: [
    ['@estruyf/github-actions-reporter', <GitHubActionOptions>{
      title: 'My custom title',
      useDetails: true,
      showError: true,
      report: ['pass', 'skipped', 'fail', 'flaky']
    }]
  ],
});
```

You can test it out in the BETA version: `@estruyf/github-actions-reporter@1.9.0-beta.1026629`

**Comment by fspinillo** [comment]
@estruyf just tested this out and it works great. Thank you so much for offering this!

**Comment by estruyf** [comment]
Thanks @fspinillo, just thinking about the `report` property name if that is clear enough. Other suggestions:

- `reportOutcomes`
- `includeResults`
- `summaryTypes`
- `resultTypes`

**Comment by fspinillo** [comment]
I think `includeResults` might be the best b/c it's a little more clear on exactly what the property does. After that I'd go with `resultTypes`.

**Comment by estruyf** [comment]
@fspinillo version 1.9.0 just got released with `includeResults` as the property name. Thanks again for suggesting this enhancement.

**Comment by fspinillo** [comment]
So Awesome, and thanks again for doing this!
