### ISSUE TITLE
TS7016 import issue "TS7016: Could not find a declaration file for module @estruyf/github-actions-reporter"

### ISSUE THREAD

**Issue by RomaSha2010** [estruyf/playwright-github-actions-reporter#20]
Hello. I'm facing this issue in the playwright.config.ts file. Please see the screenshot.

![image](https://github.com/user-attachments/assets/c4aa54c0-9b76-43a0-aefe-766fb5530855)

I've tried to execute the proposed `npm` command from the screenshot above but no luck.

 And bellow my tscofig.json file
![image](https://github.com/user-attachments/assets/ba15a318-9f95-48ef-974a-1f58338abf39)

**Comment by estruyf** [comment]
Thanks for opening the issue @RomaSha2010. I will include the file in the new version.

**Comment by estruyf** [comment]
`v1.9.1` should now contain the declaration file.

**Comment by RomaSha2010** [comment]
@estruyf thank you for the quick version update.
But I'm seeing the following issues after update
![image](https://github.com/user-attachments/assets/e425e70d-93e9-42fc-bcf6-554501607488)

I'm did what was suggested and seeing following 
![image](https://github.com/user-attachments/assets/04a8d2dc-e6d7-436c-8c99-2be509d1afd4)

![image](https://github.com/user-attachments/assets/61380430-6ded-4ad0-bd05-53c1f8b999a1)

**Comment by estruyf** [comment]
You are correct, It's weird that it worked on my end, but I forgot the export. I have included it in version 1.9.2.

**Comment by RomaSha2010** [comment]
@estruyf Thank you! That helps!
