### ISSUE TITLE
Unable to run the item within a docker container

### ISSUE THREAD

**Issue by manishmitra13** [estruyf/playwright-github-actions-reporter#5]
We ran the playwright test within the container and exporting the results into a particular location , Is it possible to point this plugin to point to a location to generate the report for GitHub?

Currently I dont think we have leverage to point the reporter to a custom location.

**Comment by estruyf** [comment]
@manishmitra13, thanks for opening the issue. It is true that it currently does not have a custom location as it writes directly to the GitHub Summary.

Will have to check what we can do when the reporter runs within a container.

**Comment by estruyf** [comment]
Do you run it like the following example: https://playwright.dev/python/docs/ci-intro#via-containers

**Comment by estruyf** [comment]
Closing the issue, in case there is more feedback, feel free to reopen it.
